---
- name: Push SSH key to system.
  authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ ssh_key }}"

- name: Add Git Maintainers repository.
  apt_repository:
    repo: 'ppa:git-core/ppa'
  become: yes

- name: Add pi-rho developer repository.
  apt_repository:
    repo: 'ppa:pi-rho/dev'
  become: yes

- name: Update aptitude.
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install common software packages.
  apt:
    name: "{{ item }}"
    state: latest
  with_items: 
    - git
    - zsh
    - tmux
    - vim
    - curl
  become: yes
